# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Welcome Application build and deploy using Azure pipeline!
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Maven@3
  displayName: Build Docker Image
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-boot:build-image'
    publishJUnitResults: false
    jdkVersionOption: 1.8
    